name: Atualizacao Diaria de Loterias Automatizada

on:
  schedule:
    # Roda de forma automática todos os dias às 23:00 (Horário de Brasília = 02:00 UTC)
    - cron: '0 2 * * *'
  workflow_dispatch: # Permite que você clique em um botão no site do GitHub para rodar quando quiser

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o codigo do seu repositorio
      uses: actions/checkout@v4

    - name: Configurar o Python no servidor da nuvem
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar as bibliotecas necessarias
      run: |
        pip install requests pandas openpyxl

    - name: Executar o script de atualizacao das loterias
      run: python atualizar_resultados.py

    - name: Salvar planilhas novas e forcar deploy automatico na Vercel
      run: |
        git config --global user.name "Loterias Bot"
        git config --global user.email "loterias-bot@github.com"
        git add historicoresultadosloteriasnacionais/*
        git commit -m "Bot: Planilhas atualizadas automaticamente [skip ci]" || echo "Nenhuma alteracao encontrada"
        git push origin main
