[server]
port = $PORT
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[client]
showErrorDetails = true

[theme]
base = "dark"

[browser]
gatherUsageStats = false
